name: Create Production Builds

on:
  push:
    branches: [main]

jobs:
  build_android:
    type: build
    params:
      platform: android
  build_ios:
    type: build
    params:
      platform: ios
  submit_android:
    type: submit
    params:
      platform: android
    after:
      - build_android
  submit_ios:
    type: submit
    params:
      platform: ios
    after:
      - build_ios
